# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20171125_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificaiton_type',
            field=models.CharField(choices=[('Like', 'LIKE'), ('Comment', 'COMMENT'), ('Follow', 'FOLLOW')], max_length=20),
        ),
    ]
